export const cfg_images = {
    short: [{ src: "./gallery/(4).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(9).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(12).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(24).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(36).png", alt: "img", title: "Title", description: "Description", price: 0 },
    ],


    services: [
        { src: "./gallery/(1).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(2).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(3).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(4).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(5).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(6).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(7).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(8).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(9).png", alt: "img", title: "Title", description: "Description", price: 0 },
    ],

    gallery: [
        { src: "./gallery/(1).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(2).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(3).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(4).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(5).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(6).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(7).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(8).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(9).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(10).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(11).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(12).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(13).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(14).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(15).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(16).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(17).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(18).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(19).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(20).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(21).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(22).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(23).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(24).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(25).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(26).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(27).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(28).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(29).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(30).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(31).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(32).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(33).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(34).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(35).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(36).png", alt: "img", title: "Title", description: "Description", price: 0 },
    ]
}