export const cfg_images = {
    short: [{ src: "./gallery/(4).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(9).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(12).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(24).png", alt: "img", title: "Title", description: "Description", price: 0 },
       { src: "./gallery/(36).png", alt: "img", title: "Title", description: "Description", price: 0 },
    ],


    services: [
        { src: "./gallery/(1).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(2).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(3).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(4).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(5).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(6).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(7).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(8).png", alt: "img", title: "Title", description: "Description", price: 0 },
        { src: "./gallery/(9).png", alt: "img", title: "Title", description: "Description", price: 0 },
    ],

    gallery: [
        { src: "./gallery/(1).png", alt: "img", title: "#1", description: "Description", price: 0 },
        { src: "./gallery/(2).png", alt: "img", title: "#2", description: "Description", price: 0 },
        { src: "./gallery/(3).png", alt: "img", title: "#3", description: "Description", price: 0 },
        { src: "./gallery/(4).png", alt: "img", title: "#4", description: "Description", price: 0 },
        { src: "./gallery/(5).png", alt: "img", title: "#5", description: "Description", price: 0 },
        { src: "./gallery/(6).png", alt: "img", title: "#6", description: "Description", price: 0 },
        { src: "./gallery/(7).png", alt: "img", title: "#7", description: "Description", price: 0 },
        { src: "./gallery/(8).png", alt: "img", title: "#8", description: "Description", price: 0 },
        { src: "./gallery/(9).png", alt: "img", title: "#9", description: "Description", price: 0 },
        { src: "./gallery/(10).png", alt: "img", title: "#10", description: "Description", price: 0 },
        { src: "./gallery/(11).png", alt: "img", title: "#11", description: "Description", price: 0 },
        { src: "./gallery/(12).png", alt: "img", title: "#12", description: "Description", price: 0 },
        { src: "./gallery/(13).png", alt: "img", title: "#13", description: "Description", price: 0 },
        { src: "./gallery/(14).png", alt: "img", title: "#14", description: "Description", price: 0 },
        { src: "./gallery/(15).png", alt: "img", title: "#15", description: "Description", price: 0 },
        { src: "./gallery/(16).png", alt: "img", title: "#16", description: "Description", price: 0 },
        { src: "./gallery/(17).png", alt: "img", title: "#17", description: "Description", price: 0 },
        { src: "./gallery/(18).png", alt: "img", title: "#18", description: "Description", price: 0 },
        { src: "./gallery/(19).png", alt: "img", title: "#19", description: "Description", price: 0 },
        { src: "./gallery/(20).png", alt: "img", title: "#20", description: "Description", price: 0 },
        { src: "./gallery/(21).png", alt: "img", title: "#21", description: "Description", price: 0 },
        { src: "./gallery/(22).png", alt: "img", title: "#22", description: "Description", price: 0 },
        { src: "./gallery/(23).png", alt: "img", title: "#23", description: "Description", price: 0 },
        { src: "./gallery/(24).png", alt: "img", title: "#24", description: "Description", price: 0 },
        { src: "./gallery/(25).png", alt: "img", title: "#25", description: "Description", price: 0 },
        { src: "./gallery/(26).png", alt: "img", title: "#26", description: "Description", price: 0 },
        { src: "./gallery/(27).png", alt: "img", title: "#27", description: "Description", price: 0 },
        { src: "./gallery/(28).png", alt: "img", title: "#28", description: "Description", price: 0 },
        { src: "./gallery/(29).png", alt: "img", title: "#29", description: "Description", price: 0 },
        { src: "./gallery/(30).png", alt: "img", title: "#30", description: "Description", price: 0 },
        { src: "./gallery/(31).png", alt: "img", title: "#31", description: "Description", price: 0 },
        { src: "./gallery/(32).png", alt: "img", title: "#32", description: "Description", price: 0 },
        { src: "./gallery/(33).png", alt: "img", title: "#33", description: "Description", price: 0 },
        { src: "./gallery/(34).png", alt: "img", title: "#34", description: "Description", price: 0 },
        { src: "./gallery/(35).png", alt: "img", title: "#35", description: "Description", price: 0 },
        { src: "./gallery/(36).png", alt: "img", title: "#36", description: "Description", price: 0 },
    ]
}